export const REQUEST_DATA = 'HOMEPAGE/ORDER/REQUEST_DATA';
export const REQUEST_DATA_SUCCESS =
  'HOMEPAGE/ORDER/REQUEST_DATA_SUCCESS';
export const REQUEST_DATA_ERROR = 'HOMEPAGE/ORDER/REQUEST_DATA_ERROR';